create database TapLuatHCG
go

use TapLuatHCG
go

create table TapLuat
(
	maLuat nchar(10) primary key not null,
	veTrai nvarchar(10) not null,
	vePhai nvarchar(10) not null
)

create table SuKien
(
	maSK nchar(10) primary key not null,
	moTa nvarchar(30) not null,
)

insert into SuKien values('A1',N'Phần cứng')
insert into SuKien values('A2',N'Phần mềm')
insert into SuKien values('A3',N'Thiết bị ngoại vi')
insert into SuKien values('B4',N'Loa Ngoài')
insert into SuKien values('B5',N'Loa Trong(trên)')
insert into SuKien values('B6',N'Camera trước')
insert into SuKien values('B7',N'Camera sau')
insert into SuKien values('B8',N'Màn hình')
insert into SuKien values('B9',N'Cảm biến')
insert into SuKien values('B10',N'Chân sạc pin')
insert into SuKien values('B11',N'Đèn flash')
insert into SuKien values('B12',N'Nút nguồn')
insert into SuKien values('B13',N'Nút tăng giảm âm lượng')
insert into SuKien values('B14',N'Bộ sạc pin')
insert into SuKien values('B15',N'Tai nghe')
insert into SuKien values('B16',N'Sim')
insert into SuKien values('B17',N'Khe sim')
insert into SuKien values('B18',N'Pin')
insert into SuKien values('B19',N'Ram')
insert into SuKien values('B20',N'Chip')
insert into SuKien values('B21',N'Main')
insert into SuKien values('B22',N'Nút vân tay')
insert into SuKien values('B23',N'Bluetooth')
insert into SuKien values('B24',N'Airdrop')
insert into SuKien values('B25',N'Call')
insert into SuKien values('B26',N'Sóng')
insert into SuKien values('C28',N'Android')
insert into SuKien values('C29',N'IOS')
insert into SuKien values('D30',N'Sáng')
insert into SuKien values('D31',N'Tối')
insert into SuKien values('D32',N'Bật')
insert into SuKien values('D33',N'Tắt')
insert into SuKien values('D34',N'Ẩm ướt')
insert into SuKien values('D35',N'Khô')
insert into SuKien values('D36',N'Phản hồi')
insert into SuKien values('D37',N'Không phản hồi')
insert into SuKien values('D38',N'Rè')
insert into SuKien values('D39',N'Chập chờn')
insert into SuKien values('D40',N'Vỡ')
insert into SuKien values('D41',N'Bình thường')
insert into SuKien values('D42',N'Phồn')
insert into SuKien values('D43',N'Đơ')
insert into SuKien values('E45',N'Hỏng loa')
insert into SuKien values('E46',N'Hỏng mic')
insert into SuKien values('E47',N'Hỏng camera')
insert into SuKien values('E48',N'Hỏng màn hình')
insert into SuKien values('E49',N'Hỏng chân sạc')
insert into SuKien values('E50',N'Hỏng bộ sạc')
insert into SuKien values('E51',N'Hỏng pin')
insert into SuKien values('E52',N'Lỗi phần mềm')
insert into SuKien values('E53',N'Bộ xử lý yếu')
insert into SuKien values('E55',N'Hỏng tai nghe')
insert into SuKien values('E56',N'Hỏng giác cắm 3.5mm')
insert into SuKien values('E57',N'Lỗi nguồn')
insert into SuKien values('E58',N'Hỏng phím main')
insert into SuKien values('E59',N'Hỏng vân tay')
insert into SuKien values('E60',N'Lỗi kết nối')
insert into SuKien values('E61',N'Lỗi cảm biến')
insert into SuKien values('E62',N'Hỏng đèn flash')
insert into SuKien values('E63',N'Phần cứng yếu')

select * from SuKien

insert into TapLuat values ('R1','A1','B4')
insert into TapLuat values ('R2','A1','B5')
insert into TapLuat values ('R3','A1','B6')
insert into TapLuat values ('R4','A1','B7')
insert into TapLuat values ('R5','A1','B8')
insert into TapLuat values ('R6','A1','B9')
insert into TapLuat values ('R7','A2','B9')
insert into TapLuat values ('R8','A1','B10')
insert into TapLuat values ('R9','A1','B11')
insert into TapLuat values ('R10','A1','B12')
insert into TapLuat values ('R11','A1','B13')
insert into TapLuat values ('R12','A1','B14')
insert into TapLuat values ('R13','A1','B15')
insert into TapLuat values ('R14','A1','B16')
insert into TapLuat values ('R15','A1','B17')
insert into TapLuat values ('R16','A1','B18')
insert into TapLuat values ('R17','A1','B19')
insert into TapLuat values ('R18','A1','B20')
insert into TapLuat values ('R19','A1','B21')
insert into TapLuat values ('R20','A1','B22')
insert into TapLuat values ('R21','A2,C28','B23')
insert into TapLuat values ('R22','A2,C29','B24')
insert into TapLuat values ('R23','A2','B25')
insert into TapLuat values ('R24','A1','B26')
insert into TapLuat values ('R25','A2','B6')
insert into TapLuat values ('R26','A1','B27')
insert into TapLuat values ('R27','B4,D37','E45')
insert into TapLuat values ('R28','B5,D37','E45')
insert into TapLuat values ('R29','B4,D36,D38','E45')
insert into TapLuat values ('R30','B6,D40','E47')
insert into TapLuat values ('R31','B7,D40','E47')
insert into TapLuat values ('R32','B8,D40','E48')
insert into TapLuat values ('R33','B8,D37','E48')
insert into TapLuat values ('R34','B9,D37','E61')
insert into TapLuat values ('R35','B10,D40','E49')
insert into TapLuat values ('R36','B10,D34','E49')
insert into TapLuat values ('R37','B10,D35,D37','E50')
insert into TapLuat values ('R38','B11,D32,D31','E62')
insert into TapLuat values ('R39','B12,D37','E58')
insert into TapLuat values ('R40','B13,D37','E58')
insert into TapLuat values ('R41','B14,D34','E50')
insert into TapLuat values ('R42','E14,D39','E49')
insert into TapLuat values ('R43','B15,D37','E55')
insert into TapLuat values ('R44','B15,D37,-E55','E56')
insert into TapLuat values ('R45','B16,D34','E58')
insert into TapLuat values ('R46','B17,D34','E58')
insert into TapLuat values ('R47','B18,D34','E51')
insert into TapLuat values ('R48','B18,D42','E51')
insert into TapLuat values ('R49','A2,D37','E63')
insert into TapLuat values ('R50','B21,D34','E58')
insert into TapLuat values ('R51','B22,D37','E59')
insert into TapLuat values ('R52','B22,D40','E59')
insert into TapLuat values ('R53','B23,D32,D37','E60')
insert into TapLuat values ('R54','B24,D32,D37','E60')
insert into TapLuat values ('R55','B8,D43','E52')
insert into TapLuat values ('R56','B25,D37','E60')
insert into TapLuat values ('R57','B25,DD39','E60')
insert into TapLuat values ('R58','B26,D37','E60')
insert into TapLuat values ('R59','B26,D39','E60')
insert into TapLuat values ('R60','E51','E57')
insert into TapLuat values ('R61','E62','E47')
insert into TapLuat values ('R62','E63','E52')

select * from TapLuat
